# Generated by Django 4.1.7 on 2024-01-14 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_level_user_current_level_user_next_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='img',
            field=models.ImageField(default=datetime.datetime(2024, 1, 14, 12, 38, 13, 761451, tzinfo=datetime.timezone.utc), upload_to='levels/imgs/'),
            preserve_default=False,
        ),
    ]
