# Generated by Django 4.1.7 on 2024-01-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_level_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_level', to='core.level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='next_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_level', to='core.level'),
            preserve_default=False,
        ),
    ]
