# Generated by Django 4.1.7 on 2024-01-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_current_level_alter_user_next_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
