# Generated by Django 4.1.7 on 2024-01-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_achieved_daily_task_user_achieved_daily_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_target',
            field=models.CharField(choices=[('15mins', '15 mins'), ('30mins', '30 mins'), ('1hour', '1 hour'), ('2hours', '2 hours'), ('4hours', '4 hours'), ('8hours', '8 hours'), ('16hours', '16 hours'), ('24hours', '24 hours')], max_length=10),
        ),
    ]
