# Generated by Django 4.1.7 on 2024-01-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
