# Generated by Django 4.1.7 on 2024-01-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_plan_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='game',
        ),
    ]
