# Generated by Django 4.1.7 on 2024-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiring_date',
            field=models.DateField(null=True),
        ),
    ]
