# Generated by Django 3.2.22 on 2023-12-04 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frequently_asked_questions', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='media/1048227_1_AMADpCo.png', upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Multiplayer', 'Multiplayer'), ('Single player', 'Single player')], max_length=50)),
                ('how_to_play', models.TextField(max_length=500)),
                ('game_points', models.IntegerField()),
                ('released_date', models.DateField(null=True)),
                ('category', models.ManyToManyField(related_name='game_category', to='Security_Cube_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackandRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_feedback', to='Security_Cube_app.games')),
            ],
        ),
    ]
