# Generated by Django 3.2.22 on 2023-12-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Security_Cube_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackandrate',
            name='userRate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userRate', to=settings.AUTH_USER_MODEL),
        ),
    ]
