# Generated by Django 3.2.22 on 2023-12-05 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0002_feedbackandrate_userrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackandrate',
            name='stars',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='games',
            name='pic',
            field=models.ImageField(default='1048227_1_AMADpCo.png', upload_to='Games'),
        ),
    ]
