# Generated by Django 3.2.22 on 2023-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0003_auto_20231205_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_file',
            field=models.FileField(default=None, upload_to='GamesFiles'),
            preserve_default=False,
        ),
    ]
