# Generated by Django 3.2.22 on 2023-12-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0005_auto_20231205_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyaskedquestions',
            options={'ordering': ['-id']},
        ),
    ]
