# Generated by Django 3.2.22 on 2023-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0006_alter_frequentlyaskedquestions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_file',
            field=models.URLField(),
        ),
    ]
