# Generated by Django 3.2.22 on 2023-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0010_auto_20231218_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackandrate',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
