# Generated by Django 3.2.22 on 2023-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0011_feedbackandrate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackandrate',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
