# Generated by Django 4.1.7 on 2024-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0013_subscribeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
