# Generated by Django 4.1.7 on 2024-01-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0014_games_premium'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='premium_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
    ]
