# Generated by Django 4.1.7 on 2024-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Cube_app', '0015_games_premium_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.RemoveField(
            model_name='games',
            name='premium',
        ),
    ]
