# Generated by Django 4.1.7 on 2024-01-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_expiring_date'),
        ('Security_Cube_app', '0016_contactreason_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='premium_plan',
        ),
        migrations.AddField(
            model_name='games',
            name='premium_plan',
            field=models.ManyToManyField(to='subscription.plan'),
        ),
    ]
